### ISSUE TITLE
关于调用c++动态文件库

### ISSUE THREAD

**Issue by chengdonglin** [wzdxy/electron-ffi-demo#2]
我通过node-gyp rebuild把ffi和ref编译成符合electron调用的版本，然后在vs里构建好我的dll文件，在js里调用的时候报了以下错误：
Uncaught Error: Dynamic Linking Error: Win32 error 193   at new DynamicLibrary
都是在x64下的。请问这个问题怎么解决？

**Comment by hehaipeng** [comment]
> 我通过node-gyp rebuild把ffi和ref编译成符合electron调用的版本，然后在vs里构建好我的dll文件，在js里调用的时候报了以下错误：
> Uncaught Error: Dynamic Linking Error: Win32 error 193 at new DynamicLibrary
> 都是在x64下的。请问这个问题怎么解决？

我也遇到这个问题，楼主能否知道一下？

**Comment by chengdonglin** [comment]
我也没搞定,已经放弃了,重写接口了.

**Comment by sunlianlong** [comment]
关于这个问题参考[Node.js调用C++动态库](https://www.jianshu.com/p/5af3ad2b0856)，里面有错误说明和解决方案
![image](https://user-images.githubusercontent.com/22101668/51165014-cb57a780-18d9-11e9-932f-49373f893581.png)
