### ISSUE TITLE
打包后的项目：Uncaught Error: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by LNyears** [wzdxy/electron-ffi-demo#3]
你好请教你一下
electron：3.0.0 x64
node: 11.8.0 x64
dll x64
打的包也是64的，安装运行应用就报：Uncaught Error: Dynamic Linking Error: Win32 error 126；
本地跑起来一切正常，打包后就是不行，能否知道一下啊，谢谢！
   return ffi.Library('../../../dll/MyDLL.dll', {
        'Add': ['float', ['float', 'float']],
        'Hello': ['string', []],
        'StrLength': ['int', ['string']]
      })
dll文件是放在项目根目录下的；如果按你的demo来build的话请问这里该怎么配置啊：
"extraFiles": [
      "dll"
    ]

**Comment by wzdxy** [comment]
已经更新成了 ffi-napi可以尝试一下

**Comment by haoxl3** [comment]
@LNyears 请问您后来怎么解决的？不想升级为fii-napi，我也是ffi

**Comment by LNyears** [comment]
> @LNyears 请问您后来怎么解决的？不想升级为fii-napi，我也是ffi

Dynamic Linking Error: Win32 error 126---这个错误有三种原因

1\.1 通常是传入的DLL路径错误，找不到Dll文件，推荐使用绝对路径。

1\.2 如果是在x64的node/electron下引用32位的DLL，也会报这个错，反之亦然。要确保DLL要求的CPU架构和你的运行环境相同。

1\.3 DLL还有引用其他DLL文件，但是找不到引用的DLL文件，可能是VC依赖库或者多个DLL之间存在依赖关系。

我遇到的是第三种情况， 你可以对应检查检查
