### ISSUE TITLE
 ffi.Library的时候, 加载方法的问题

### ISSUE THREAD

**Issue by hudongya** [wzdxy/electron-ffi-demo#4]
加载对应的方法, 方法需要有出参入参('Add': ['float', ['float', 'float']]) ,  第一个是返回的结果类型 ,  不返回的时候需要写什么类型,  我试了空\null\undefined  ,  都是报错. 不知道js调用c++有没有对应的参数类型写法?

**Comment by gwerghh** [comment]
'Add': ['void', ['float', 'float']]

**Comment by hudongya** [comment]
。
